from .team import Team
from .NED import NED
from .IND import IND
from .AUS import AUS
from .GER import GER
from .BEL import BEL
from .ENG import ENG
from .ESP import ESP
from .ARG import ARG
from .RSA import RSA
from .PAK import PAK
from .NZL import NZL
from .IRL import IRL
from .WAL import WAL
from .AUT import AUT
from .MAL import MAL
from .SCO import SCO